package assets.paraknight.steambikes.client;

import assets.paraknight.steambikes.EntitySteamBike;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelSteamBike extends ModelBase {
	private ModelRenderer frontWheel;
	private ModelRenderer wheelMatrix;
	private ModelRenderer backWheel;
	private ModelRenderer backAxis;
	private ModelRenderer bottomAxis;
	private ModelRenderer lowerAxis;
	private ModelRenderer upperAxis;
	private ModelRenderer frontAxis;
	private ModelRenderer leftHandleBar;
	private ModelRenderer rightHandleBar;
	private ModelRenderer leftHandleGrip;
	private ModelRenderer rightHandleGrip;
	private ModelRenderer frontTankConnector;
	private ModelRenderer tank;
	private ModelRenderer backTankConnector;
	private ModelRenderer leftFootRest;
	private ModelRenderer mainAxis;
	private ModelRenderer leftCargo;
	private ModelRenderer rightFootRest;
	private ModelRenderer rightCargo;
	private ModelRenderer centralCoupler;
	private ModelRenderer seatArm;
	private ModelRenderer seat;
    private ModelRenderer headLamps;
    private ModelRenderer hud;
    private ModelRenderer headLampArm;
      
	public ModelSteamBike() {
        frontWheel = new ModelRenderer(this);
        frontWheel.setRotationPoint(0F, 4F, -6F);
        wheelMatrix = new ModelRenderer(this, 0, 64).setTextureSize(64, 128).addBox(0F, -8F, -8F, 0, 16, 16);
        wheelMatrix.setRotationPoint(0F, 12F, -18F);
        frontWheel.addChild(wheelMatrix);
        backWheel = new ModelRenderer(this, 32, 64).setTextureSize(64, 128).addBox(0F, -8F, -8F, 0, 16, 16);
        backWheel.setRotationPoint(0F, 16F, 35F);
        backAxis = new ModelRenderer(this, 27, 57).setTextureSize(64, 128).addBox(-1F, -1F, -1F, 2, 19, 2);
        backAxis.setRotationPoint(0F, 16F, 35F);
        backAxis.rotateAngleX = -1.291544F;
        bottomAxis = new ModelRenderer(this, 0, 55).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 2, 23);
        bottomAxis.setRotationPoint(0F, 19F, -5F);
        bottomAxis.rotateAngleX = -0.05235988F;
        lowerAxis = new ModelRenderer(this, 0, 67).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 2, 9);
        lowerAxis.setRotationPoint(0F, 12F, -8F);
        lowerAxis.rotateAngleX = -1.029744F;
        upperAxis = new ModelRenderer(this, 0, 64).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 10, 2);
        upperAxis.setRotationPoint(0F, 4F, -6F);
        upperAxis.rotateAngleX = -0.4014257F;
        frontAxis = new ModelRenderer(this, 35, 53).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 23, 2);
        frontAxis.setRotationPoint(0F, 4F, -6F);
        frontAxis.rotateAngleX = -1.047198F;
        leftHandleBar = new ModelRenderer(this, 0, 51).setTextureSize(64, 128).addBox(0F, 0F, 0F, 10, 2, 2);
        leftHandleBar.setRotationPoint(0F, 4F, -6F);
        leftHandleBar.rotateAngleY = -0.5235988F;
        rightHandleBar = new ModelRenderer(this, 0, 47).setTextureSize(64, 128).addBox(-10F, 0F, 0F, 10, 2, 2);
        rightHandleBar.setRotationPoint(0F, 4F, -6F);
        rightHandleBar.rotateAngleY = 0.5235988F;
        leftHandleGrip = new ModelRenderer(this, 0, 55).setTextureSize(64, 128).addBox(9F, 0F, -3F, 7, 1, 1);
        leftHandleGrip.setRotationPoint(0F, 4F, -6F);
        leftHandleGrip.rotateAngleY = -0.8726646F;
		leftHandleGrip.rotateAngleZ = 0.05235988F;
        rightHandleGrip = new ModelRenderer(this, 0, 57).setTextureSize(64, 128).addBox(-16F, 0F, -3F, 7, 1, 1);
        rightHandleGrip.setRotationPoint(0F, 4F, -6F);
        rightHandleGrip.rotateAngleY = 0.8726646F;
		rightHandleGrip.rotateAngleZ = -0.05235988F;
        frontTankConnector = new ModelRenderer(this, 8, 60).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 2, 5);
        frontTankConnector.setRotationPoint(0F, 16F, -6F);
        frontTankConnector.rotateAngleX = -0.05235988F;
        tank = new ModelRenderer(this, 0, 25).setTextureSize(64, 128).addBox(-3F, -2F, 5F, 6, 5, 17);
        tank.setRotationPoint(0F, 16F, -6F);
        tank.rotateAngleX = -0.05235988F;
        backTankConnector = new ModelRenderer(this, 29, 30).setTextureSize(64, 128).addBox(-1F, 0F, 22F, 2, 2, 10);
        backTankConnector.setRotationPoint(0F, 16F, -6F);
        backTankConnector.rotateAngleX = -0.05235988F;
        leftFootRest = new ModelRenderer(this, 0, 39).setTextureSize(64, 128).addBox(1F, 1F, 0F, 6, 1, 2);
        leftFootRest.setRotationPoint(0F, 16F, -6F);
        leftFootRest.rotateAngleX = -0.3665192F;
		leftFootRest.rotateAngleY = -0.2094395F;
        mainAxis = new ModelRenderer(this, 58, 45).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 34, 1);
        mainAxis.setRotationPoint(0F, 7F, -6F);
        mainAxis.rotateAngleX = 1.22173F;
        leftCargo = new ModelRenderer(this, 0, 96).setTextureSize(64, 128).addBox(1F, -8F, -2F, 3, 6, 10);
        leftCargo.setRotationPoint(0F, 16F, -6F);
        leftCargo.rotateAngleX = -0.05235988F;
        rightFootRest = new ModelRenderer(this, 0, 36).setTextureSize(64, 128).addBox(-7F, 1F, 0F, 6, 1, 2);
        rightFootRest.setRotationPoint(0F, 16F, -6F);
        rightFootRest.rotateAngleX = -0.3665192F;
		rightFootRest.rotateAngleY = 0.2094395F;
        rightCargo = new ModelRenderer(this, 26, 96).setTextureSize(64, 128).addBox(-4F, -8F, -2F, 3, 6, 10);
        rightCargo.setRotationPoint(0F, 16F, -6F);
        rightCargo.rotateAngleX = -0.05235988F;
        centralCoupler = new ModelRenderer(this, 16, 98).setTextureSize(64, 128).addBox(-3F, -5F, 8F, 4, 3, 5);
        centralCoupler.setRotationPoint(1F, 16F, -6F);
        centralCoupler.rotateAngleX = -0.05235988F;
        seatArm = new ModelRenderer(this, 50, 62).setTextureSize(64, 128).addBox(-1F, 0F, 0F, 2, 16, 2);
        seatArm.setRotationPoint(0F, 15F, 7F);
        seatArm.rotateAngleX = 1.850049F;
        seat = new ModelRenderer(this, 0, 8).setTextureSize(64, 128).addBox(-3F, 0F, 0F, 6, 3, 14);
        seat.setRotationPoint(0F, 8F, 11F);
        seat.rotateAngleX = 0.03490658F;
        headLamps = new ModelRenderer(this, 29, 35).setTextureSize(64, 128).addBox(-1.5F, -1.5F, -2F, 3, 3, 2);
        headLamps.setRotationPoint(0F, 4F, -6F);
        headLamps.rotateAngleX = -0.1047198F;
        hud = new ModelRenderer(this, 0, 30).setTextureSize(64, 128).addBox(-3F, 1F, 3F, 6, 5, 1);
        hud.setRotationPoint(0F, 4F, -6F);
        hud.rotateAngleX = 0.4363323F;
        headLampArm = new ModelRenderer(this, 29, 31).setTextureSize(64, 128).addBox(-0.5F, -1F, -1F, 1, 1, 3);
        headLampArm.setRotationPoint(0F, 4F, -6F);
        headLampArm.rotateAngleX = -0.6632251F;
      }

	public void render(EntitySteamBike bike) {
		frontWheel.rotateAngleY = bike.turnAngle;
		frontAxis.rotateAngleY = bike.turnAngle;
		headLamps.rotateAngleY = bike.turnAngle;
		headLampArm.rotateAngleY = bike.turnAngle;
		leftHandleBar.rotateAngleY = bike.turnAngle-0.5235988F;
		rightHandleBar.rotateAngleY = bike.turnAngle+0.5235988F;
		leftHandleGrip.rotateAngleY = bike.turnAngle-0.8726646F;
		rightHandleGrip.rotateAngleY = bike.turnAngle+0.8726646F;
		hud.rotateAngleY = bike.turnAngle;
		wheelMatrix.rotateAngleX = bike.wheelAngle;
		backWheel.rotateAngleX = bike.wheelAngle;
		float scale = 0.0625F;
        frontWheel.render(scale);
        backWheel.render(scale);
        backAxis.render(scale);
        bottomAxis.render(scale);
        lowerAxis.render(scale);
        upperAxis.render(scale);
        frontAxis.render(scale);
        leftHandleBar.render(scale);
        rightHandleBar.render(scale);
        leftHandleGrip.render(scale);
        rightHandleGrip.render(scale);
        frontTankConnector.render(scale);
        tank.render(scale);
        backTankConnector.render(scale);
        leftFootRest.render(scale);
        mainAxis.render(scale);
        leftCargo.render(scale);
        rightFootRest.render(scale);
        rightCargo.render(scale);
        centralCoupler.render(scale);
        seatArm.render(scale);
        seat.render(scale);
        headLamps.render(scale);
        hud.render(scale);
        headLampArm.render(scale);
      }
}